# Generated by Django 5.2.4 on 2025-08-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись блога', 'verbose_name_plural': 'Записи блога'},
        ),
    ]
