# Generated by Django 5.2.4 on 2025-08-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_review_user', 'Can review user'), ('can_recommend_user', 'Can recommend user')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
