# Generated by Django 5.2.4 on 2025-07-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
