# Generated by Django 5.2.4 on 2025-08-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_review_categoru', 'Can review categoru'), ('can_recommend_categoru', 'Can recommend categoru')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
