# Generated by Django 5.2.4 on 2025-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы сделать продукт видимым для всех пользователей', verbose_name='Опубликовано'),
        ),
    ]
